USE master
GO
if exists (select * from sysdatabases where name='task1')
	DROP DATABASE task1
GO

CREATE DATABASE task1
GO
USE task1
GO

----- Tables -----
CREATE TABLE PRODUCT (
  MAKER CHAR(1) NOT NULL ,
  MODEL VARCHAR(4) NOT NULL ,
  TYPE VARCHAR(7) NOT NULL 
);

CREATE TABLE PRINTER(
  CODE INT NOT NULL ,
  MODEL VARCHAR(4) NOT NULL ,
  PRICE FLOAT NOT NULL 
);

---Product
INSERT INTO PRODUCT(MAKER, MODEL, TYPE) 
	VALUES ('A','L123','Printer');
INSERT INTO PRODUCT(MAKER, MODEL, TYPE) 
	VALUES ('A','M222','Printer');
INSERT INTO PRODUCT(MAKER, MODEL, TYPE) 
	VALUES ('B','J333','Printer');
INSERT INTO PRODUCT(MAKER, MODEL, TYPE) 
	VALUES ('B','J335','Printer');

---Printer
INSERT INTO PRINTER (CODE, MODEL, PRICE)
	VALUES (1, 'L123', '399');
INSERT INTO PRINTER (CODE, MODEL, PRICE)
	VALUES (2, 'M222', '420');
INSERT INTO PRINTER (CODE, MODEL, PRICE)
	VALUES (3, 'J333', '500');
INSERT INTO PRINTER (CODE, MODEL, PRICE)
	VALUES (4, 'J335', '650');

ALTER TABLE PRINTER 
	ADD TYPE VARCHAR(6) CHECK (TYPE IN ('laser', 'matrix', 'jet')),
		--- TYPE ENUM('laser', 'matrix', 'jet')
		COLOR CHAR(1) CHECK (COLOR IN ('y', 'n'));
		--- COLOR ENUM('y', 'n');

ALTER TABLE PRINTER DROP COLUMN PRICE;

DROP TABLE PRODUCT;
DROP TABLE PRINTER;