DROP TRIGGER IF EXISTS T_BOOKING_INSERT;
GO
CREATE TRIGGER T_BOOKING_INSERT ON BOOKING AFTER INSERT
AS BEGIN
    UPDATE FLIGHT
    SET NUM_PASS = NUM_PASS + 1
	FROM FLIGHT
	INNER JOIN INSERTED i ON FLIGHT.CODE = i.FLIGHT_NUMBER
	UPDATE AGENCY
    SET NUM_BOOK = NUM_BOOK + 1
	FROM AGENCY
	INNER JOIN INSERTED i ON AGENCY.NAME = i.AGENCY
END;

INSERT INTO BOOKING (CODE, AGENCY, AIRLINE_CODE, FLIGHT_NUMBER, CUSTOMER_ID, BOOKING_DATE, FLIGHT_DATE, PRICE, STATUS)
	VALUES (504, 'TravelWorld', 1, 301, 401, '2023-10-11 08:00:00', 
			'2023-11-11 12:00:00', 500.00, '1');

INSERT INTO BOOKING (CODE, AGENCY, AIRLINE_CODE, FLIGHT_NUMBER, CUSTOMER_ID, BOOKING_DATE, FLIGHT_DATE, PRICE, STATUS)
	VALUES (505, 'TravelWorld', 1, 302, 401, '2023-10-11 08:00:00', 
			'2023-11-11 12:00:00', 450.00, '1');

INSERT INTO BOOKING (CODE, AGENCY, AIRLINE_CODE, FLIGHT_NUMBER, CUSTOMER_ID, BOOKING_DATE, FLIGHT_DATE, PRICE, STATUS)
	VALUES (506, 'TravelWorld', 1, 302, 401, '2023-10-11 08:00:00', 
			'2023-11-11 12:00:00', 450.00, '1');

INSERT INTO BOOKING (CODE, AGENCY, AIRLINE_CODE, FLIGHT_NUMBER, CUSTOMER_ID, BOOKING_DATE, FLIGHT_DATE, PRICE, STATUS)
	VALUES (507, 'TravelWorld', 1, 302, 401, '2023-10-11 08:00:00', 
			'2023-11-11 12:00:00', 450.00, '1');

DROP TRIGGER IF EXISTS T_BOOKING_DELETE;
GO
CREATE TRIGGER T_BOOKING_DELETE ON BOOKING AFTER DELETE
AS BEGIN
    UPDATE FLIGHT
    SET NUM_PASS = NUM_PASS - 1
	WHERE FLIGHT.CODE in (SELECT FLIGHT_NUMBER FROM DELETED)
	UPDATE AGENCY
    SET NUM_BOOK = NUM_BOOK - 1
	FROM AGENCY
	WHERE AGENCY.NAME in (SELECT AGENCY FROM DELETED)
END;

--DELETE FROM BOOKING WHERE CODE IN (504,505,506)

DROP TRIGGER IF EXISTS T_BOOKING_STATUS_UPDATE;
GO
CREATE TRIGGER T_BOOKING_STATUS_UPDATE ON BOOKING AFTER UPDATE
AS BEGIN
    UPDATE FLIGHT
    SET NUM_PASS = NUM_PASS + 1
    FROM FLIGHT f
    INNER JOIN INSERTED i on i.FLIGHT_NUMBER = f.CODE
    WHERE i.STATUS = '1'
    
    UPDATE FLIGHT
    SET NUM_PASS = NUM_PASS - 1
    FROM FLIGHT f
    INNER JOIN INSERTED i on i.FLIGHT_NUMBER = f.CODE
    WHERE i.STATUS = '0'
END;

UPDATE BOOKING
SET STATUS = '0'
WHERE CODE = 501;

select * from FLIGHT;
select * from AGENCY;
select * from BOOKING;


 